### PR TITLE
Fixes #129

### LINKED ISSUE #129: [New Feature]: Adding Auto-commenting feature for PR raised
### 🎮 feature Request

- When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. 
- However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.
- This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. 
- This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

### Point down the features

- This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs.
- By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. 
- This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
## PR Description 📜

This PR adds an auto-commenting feature, which auto-comments when new PRs are raised.

Fixes #129 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Sir kindly review the PR and merge it.
Thank you!

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Could you please add this msg also "Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. Don't forget to follow us on [LinkedIn](https://www.linkedin.com/company/chromegaming), [GitHub](https://github.com/GameSphere-MultiPlayer), [Discord](https://discord.gg/rZb46cCMmK)"  and so on..

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Yeah sure! I'll do it.

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Sir, I'm done with the changes. Kindly review.
Thank you!

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
