### PR TITLE
Solved issue #101- Headings like Legal, Info, Explore, etc are not visible

### LINKED ISSUE #101: [Bug]: Headings like Legal, Info, Explore, etc are not visible
### Give a brief about the bug ✍️

Description
Headings like Legal, Info, Explore, etc are not visible. They are written in black and the background is also black so the text is not visible.
Screenshot 2024-05-15 151759

### What is the expected behavior? 🤔

Description
Expected is that the text is visible. 

### Provide step by step information reproduce the bug 📄

Description
I can change the font and colour of the text to make it visible.

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below

I have changed the colour of the headings different from the background so that the text is visible.

Fixes # <your_issue_number>
Fixes #101 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
This one was assigned to me 
So kindly review and merge 
Thankyou

**Comment by Durgesh4993** [comment]
@Aditi22Bansal You have cloned old code
image

**Review by Durgesh4993 — APPROVED** [review]

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Please reclone and and make proper alignmet & grid, you code is being create conflicta

**Comment by Aditi22Bansal** [comment]
Done @Durgesh4993 
here is the screenshot
Screenshot 2024-05-22 112724

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review now
Sorry for the inconvenience
Thankyou

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review this PR 
Thankyou

**Comment by Aditi22Bansal** [comment]
@Durgesh4993
Kindly review this PR
Thankyou

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
Kindly review this PR and merge

**Comment by Aditi22Bansal** [comment]
@Durgesh4993 
I have done the changes asked by you
Please review the PR and approve
Thankyou

**Pull request merged**
