### PR TITLE
Added Logo in the header.

### LINKED ISSUE #56: [New Feature]: Logo of the website should be on appear with the name of the website in the header
### 🎮 feature Request

I will set the logo of the website aside the name of the website in the header .
Screenshot 2024-05-12 214621

### Point down the features

I will also make this responsive so that it will give best user experience in all the devices.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Coder-Kartikey**
## PR Description 📜

Added Website logo on the header.
Issue no.
Fixes #56 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Coder-Kartikey** [comment]
I have generated a pr request so please review it and tell if any changes are required or if it is ok then please approve it.

**Comment by Coder-Kartikey** [comment]
@Durgesh4993 please merge this pr so i can work on other issues.

**Comment by Durgesh4993** [comment]
@Coder-Kartikey Resolve conflict

**Comment by Coder-Kartikey** [comment]
@Durgesh4993 , I have resolved the conflict and open a new pull request #165 please review it and merge it.

**Pull request closed without merging**
