### PR TITLE
Fixed navbar

### LINKED ISSUE #108: Fixed top Navbar
### 🎮 feature Request

I would like to fix the top navbar so that it would be visible even upon scroll.

### Select program in which you are contributing

GSSOC

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Priya-49**
## PR Description 📜

Fixed top navbar to make it visible even with the scroll. 
Fixes #108 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
Screenshot (208)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Please do margin zero from left and right

**Comment by Durgesh4993** [comment]
@Priya-49 add issue number & don't foret to clone latest codes

**Comment by Priya-49** [comment]
I fixed the issue!

**Comment by Priya-49** [comment]
@Durgesh4993
I have made the requested changes.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
resolve Conflicting filesa and add demo video

**Pull request closed without merging**
