### PR TITLE
Added hovering effects to leaderboard

### LINKED ISSUE #89: [New Feature]: Hovering effect over the rank cards.
### 🎮 feature Request

The rank cards will appear to come out and have shadow effect when hovered  upon

### Point down the features

hovering over the cards will make them look stunning using shadow and color changing ,improving overall UI/UX .

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by curecode11**
## PR Description 📜
Added the much needed hovering effect over the leaderboard, without hampering the normal functioning of the project.
Fixes #89

<hr>
 
## Hovering effect over leaderboard for better visuals ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

## Screenshots
image
image

--- 
<br>

## Thank you so much for giving me the opportunity to contribute , I enjoyed doing it.

### CODE REVIEW

**Comment by curecode11** [comment]
Sir you can review the code and close the particular issue #89

**Comment by curecode11** [comment]
Sir please review the code and close the issue , its been more than 3 days I created this PR.

**Comment by Durgesh4993** [comment]
@curecode11 You have already sended PR, because hover is already working on website

**Comment by curecode11** [comment]
so  @Durgesh4993  sir will I get points according to level 1 or level 2 because I by mistake worked upon the same branch and created a pull request containing both the issues as it was a level 1 task and this is a level 2 task.

**Pull request closed without merging**
