### PR TITLE
Faq section

### PR DESCRIPTION
**Pull request by gupta-ritik**
The faq section and its responsiveness are made and the hover effect for the social-media icons is also implemented.

I trying to solve assigned work as #30 

Thank you so much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Resolve conflict & delete .vscode folder

**Comment by gupta-ritik** [comment]
Conflicts is resolve now Check it once

**Comment by gupta-ritik** [comment]
again conflicts is resolve

**Comment by gupta-ritik** [comment]
Please accept the PR request #73

**Pull request merged**
