### PR TITLE
Products page

### PR DESCRIPTION
**Pull request by Ridhima10**
Hello PA @Durgesh4993 ,
Issue resolved - #82 
i have created a  product page which follows your theme and has  parallax effect on cards also.
I have messaged on you discord but since you didn't answered  about the content inside cards ,I have created the cards with dummy data for now.
I hope you like the layout

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/85826117/e5d9d8eb-5af6-4f8d-9a9b-f48d0a850b08

Kindly merge it with main,
Best regards

### CODE REVIEW

**Comment by Manaregr8** [comment]
fsdfsdfdsfd

Well done, @Ridhima10 ! However, there are still a few points to address:

1. In smaller screen widths, the left social icons overlap with the contents of the cards. Consider adding padding or employing other methods to prevent this overlap.
2. The footer headings are detracting from the page's UI. Align these headings to the left and change their color to match that of the homepage.
3. Could you please declare an issue regarding the responsiveness of the navbar, particularly in accommodating various screen widths.

Thank You

**Comment by Ridhima10** [comment]
sure i will fix these issues as well

**Comment by Ridhima10** [comment]
@Manaregr8  Products page is up-to-date now. 
Kindly review and tell if you need any further changes. Thankyou!

**Comment by Manaregr8** [comment]
> @Manaregr8 Products page is up-to-date now. Kindly review and tell if you need any further changes. Thankyou!

Hi @Ridhima10 ,

Could you please resubmit the pull request? It appears that someone has updated the main branch, and the Product page in the repository is currently empty.

Thank you!

**Pull request merged**
