### PR TITLE
Changed the text colour of the Footer section for Dark/Light mode.

### PR DESCRIPTION
**Pull request by ayushrskiaa**
## PR Description 📜

The text of the footer section is now clearly visible in both the Dark and Light mode.
Fixes # 122

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅] My changes generates no new warnings.
- [✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayushrskiaa** [comment]
please check it and accept the pull request.
Thank you.

**Comment by Manaregr8** [comment]
Nicely Done

**Comment by ayushrskiaa** [comment]
Thank you

**Comment by ayushrskiaa** [comment]
hello @Manaregr8 I'm not able to see the changes on the webpage that I made. Is there any problem?

**Comment by ayushrskiaa** [comment]
@Manaregr8 please add the gssoc label to this PR. Thank you

**Pull request merged**
