### PR TITLE
Node.js server initialised and file structure modified

### LINKED ISSUE #187: [New Feature]: Need to create a Nodejs based backend for better functionality
### 🎮 feature Request

For a modern level website , there is always a need for a backend based on Node / Django / Php / Ruby. As this wwebsite doesn't currently have a backend , I would like to create the needful. 

### Point down the features

- The backend will be created on Nodejs and Expressjs ( JS based )
- To keep the frontend like HTML , a similar templating language **EJS** will be used , which is just like HTML
- After creating the basic backend of the website , it will be deployed on Vercel

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by sambitsingha**
# PR Description 📜

This PR just initialises the Express backend server and refactors the file structure for easier navigation. 

## This PR is not the final PR which will close #187 . This was just necessary to avoid future merge conflicts. 
kindly add the labels. The #187 issue is still in progress

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by sambitsingha** [comment]
@Durgesh4993 Please see to it

**Comment by Durgesh4993** [comment]
@sambitsingha Add a proper demo i will review it

**Comment by sambitsingha** [comment]
@Durgesh4993 See the changes I have done. This PR is just to avoid future conflicts. 


https://github.com/GameSphere-MultiPlayer/Community-Page/assets/110420002/b1be1d3c-9583-4fc1-bb44-8da93301bffc

**Comment by Durgesh4993** [comment]
Show the output ( runing website )

**Comment by sambitsingha** [comment]
> and raise new issue, proper documentation how other contributors will able setup the project

Alright

**Comment by Durgesh4993** [comment]
@sambitsingha Demo video

**Comment by sambitsingha** [comment]
@Durgesh4993 Server up and running well.

### Demo - 

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/110420002/5c7b20e8-a695-46c9-838c-e497dcf24b0e

**Comment by sambitsingha** [comment]
I am doing the changes in the README.md now. This PR can be merged. Closes Issue #187

**Comment by Durgesh4993** [comment]
Show me whole project output

**Comment by sambitsingha** [comment]
@Durgesh4993 The recorder couldn't recorded the previous clip properly.

Here is the frontend - 

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/110420002/2a1494b3-fcfe-441b-ad54-62e47823967b

**Pull request merged**
