### PR TITLE
Generated favicon.ico and added to the website.

### LINKED ISSUE #13: adding favicon
### 🎮 feature Request

feature logic and basic description

### Point down the features

feature points

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by ayushrskiaa**
## PR Description 📜

Created favicon logo and added it in the index.html.
Fixes #13 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ✅] I have commented my code, particularly in hard-to-understand areas.
- [ ✅] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by ayushrskiaa** [comment]
please check it and accept the pull request.Thank you.

**Comment by ayushrskiaa** [comment]
Thank you

**Comment by ayushrskiaa** [comment]
@Manaregr8  please add the GSSOC label to this issue.

**Comment by Manaregr8** [comment]
> @Manaregr8 please add the GSSOC label to this issue.

This is the pull request, Its issue already have that gssoc label and level2 label.

Thank you

**Comment by ayushrskiaa** [comment]
@Manaregr8 As per instructions given on the discord channel by GSSoC, PR should also be labeled, else it won't count towards the leaderboard. So please label this PR. Thank you.

**Pull request merged**
