### PR TITLE
[New Feature]: Improvement of social link to share button view . Assign under GSSOC'24

### LINKED ISSUE #76: [New Feature]: Improvement of social link to share button view . Assign under GSSOC'24
### 🎮 feature Request

Footer Share option's below email input:
image

Feature i want to improve for share option:
It reduces space and also looks attractive due it's transform.

### Point down the features

Feature i want to improve for share option:

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/abbf18c9-2a23-4bcf-a50f-83788511dacc

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Anjaliavv51**
## PR Description 📜

Feature i want to improve for share option:
It reduces space and also looks attractive due it's transform.
Fixes #76 

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸<br>
After Togle Share Button :

https://github.com/GameSphere-MultiPlayer/Community-Page/assets/154777864/cdef7c9a-4b69-49e7-8bde-e6b618b76d99

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Remove all social icons which are already exist in left side and add your there

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
image

**Review by Manaregr8 — CHANGES_REQUESTED** [review]
Nice work but there is a problem, the feature's animation works great but its responsiveness and alignment to the page is an issue please review it and fix it accordingly.
U can use doubt channel in discord if you have any.

**Comment by Manaregr8** [comment]
Also please review https://github.com/GameSphere-MultiPlayer/Community-Page/pull/86#pullrequestreview-2062120450 
he said not to remove those icons in the left, just use different icons in your feature.

**Comment by Anjaliavv51** [comment]
Sorry I didn't get u , can u please allobarate

**Comment by Anjaliavv51** [comment]
After Changes

image

**Comment by Anjaliavv51** [comment]
After Changes:

[Share Button.zip](https://github.com/GameSphere-MultiPlayer/Community-Page/files/15368987/Share.Button.zip)

**Comment by Manaregr8** [comment]
Hi @Anjaliavv51 
The share button issue has been partially resolved, but there are still a couple of problems:

1. In light mode, the share button becomes invisible.
2. The button's position is inconsistent across different screen sizes. It often overlaps with text, which affects the user experience.

Could you please use media queries to adjust the button's position based on different view widths? This would help place the button in appropriate blank spaces for various screen sizes, resulting in a more visually appealing and user-friendly feature.

**Comment by Anjaliavv51** [comment]
Okay Sure

**Comment by Anjaliavv51** [comment]
image

**Comment by Anjaliavv51** [comment]
U can check now.

**Comment by Anjaliavv51** [comment]
image

**Comment by Manaregr8** [comment]
> U can check now.

Hi @Anjaliavv51
hgfhfghfghfghfgh
,

Everything looks perfect! However, I have one request. The mobile view is great, but for the desktop view, could you please relocate the element to the position I marked in the attached image?

Thank you!

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
image

**Comment by Anjaliavv51** [comment]
Now please check once.

**Review by Anjaliavv51 — COMMENTED** [review]
Any changes required still?

**Comment by Manaregr8** [comment]
> Any changes required still?


Nope i guess its done for now

**Comment by Anjaliavv51** [comment]
Okay

**Pull request merged**
