### PR TITLE
added favicons to each and every page , also connecting them through hyperlinks.

### LINKED ISSUE #87: [Bug]: 1. Favicon absent , 2.About ,Home, Contribute page are not hyperlinked
### Give a brief about the bug ✍️

Header section links are going no where also the website is missing a favicon which always create a good impression about the site.
I can make the about and contribute page also will add the favicon .

### What is the expected behavior? 🤔

Interlinking should be there between header section links.

### Provide step by step information reproduce the bug 📄

just click on the links you will go nowhere 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by curecode11**
## PR Description 📜
Added favicons to every page, connected all the pages with hyperlinks , created playgames - contribute and products page to link them together now each page can be developed separately.
Fixes #87

<hr>
 
Following has been completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>

## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for giving me the opportunity to contribute in the project 🙏.

### CODE REVIEW

**Comment by curecode11** [comment]
Sir @Durgesh4993 I have removed all merge conflicts and made a pull request you can review the code and close the issue.

**Comment by Manaregr8** [comment]
> Sir @Manaregr8 I have removed all merge conflicts and made a pull request you can review the code and close the issue.

Please provide a working video covering favicon display in title bar, links navigation and other issues that are been resolved.

**Comment by curecode11** [comment]
> Hi @curecode11
> 
> 1. Utilize only the icon as a favicon, excluding any accompanying text. This can be accomplished by cropping and enhancing it as necessary.
> 2. Implement a circular favicon. If this option is unavailable, kindly request it via email: [manjeetdevelops@gmail.com](mailto:manjeetdevelops@gmail.com).
> 
> ddaadasdasdasdasdasd

Ok sir I will update the favicon after taking a snap of the logo given in the fauget.gif

**Comment by curecode11** [comment]
@Manaregr8 sir, successfully added round shaped favicon you can now review it.

**Pull request merged**
