### PR TITLE
Fixes #127

### LINKED ISSUE #127: [New Feature]: Adding Auto-commenting feature on Issues
### 🎮 feature Request

- When issues are created in a project, it is important to provide immediate acknowledgment and guidance to the issue creator. However, manually commenting on every newly created issue can be time-consuming for maintainers, leading to delays and inconsistency in communication. 
- This can result in contributors feeling ignored or discouraged from further participation.
- I would like an automated feature that posts a predefined comment on an issue as soon as it is created. 
- This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information.
-  The automation should be customizable to accommodate different project workflows and communication styles.

### Point down the features

- This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. 
- By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. 
- This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Sambit-Mondal**
## PR Description 📜

This PR adds an auto-commenting feature to the new issues that'll be raised.

Fixes #127 

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Sir kindly review the PR and merge it.
Thank you!

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
Could you please add this msg also "Thank you for creating this issue! We'll look into it as soon as possible. If you have any doubt you can directly send message on our [Discord](https://discord.gg/rZb46cCMmK), we have created separate channels for all projects and you will get chance to connect with mentors directly."

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 Yeah, I'll do it.

**Comment by Sambit-Mondal** [comment]
@Durgesh4993 I'm done with the changes. Kindly review.
Thank you!

**Review by Durgesh4993 — APPROVED** [review]
Approved

**Pull request merged**
